import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-title" content="Lost Cities Scores" />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
};

export default RootLayout;
